name: 🐛 Bug Report
description: Signaler un bug ou un dysfonctionnement
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug ! 
        Plus vous fournirez d'informations, plus vite nous pourrons le résoudre.

  - type: textarea
    id: description
    attributes:
      label: 📝 Description du bug
      description: Description claire et concise du problème
      placeholder: Décrivez ce qui ne fonctionne pas...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Étapes pour reproduire
      description: Étapes détaillées pour reproduire le problème
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Faire défiler jusqu'à '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Comportement attendu
      description: Que devrait-il se passer normalement ?
      placeholder: Décrivez le comportement attendu...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Comportement actuel
      description: Que se passe-t-il réellement ?
      placeholder: Décrivez ce qui se passe actuellement...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Composant affecté
      description: Quelle partie de l'application est concernée ?
      options:
        - Frontend (Interface utilisateur)
        - Backend (API/Serveur)
        - Base de données
        - Authentification
        - Configuration/Déploiement
        - Documentation
        - Autre
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Sévérité
      description: Quel est l'impact de ce bug ?
      options:
        - Critique (Application inutilisable)
        - Élevée (Fonctionnalité majeure cassée)
        - Moyenne (Fonctionnalité mineure cassée)
        - Faible (Problème cosmétique)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environnement
      description: Informations sur votre environnement
      placeholder: |
        - OS: [ex: Windows 11, macOS 13, Ubuntu 22.04]
        - Navigateur: [ex: Chrome 118, Firefox 119, Safari 17]
        - Version Node.js: [ex: 18.17.0]
        - Version Python: [ex: 3.9.7]
        - Version de l'app: [ex: v1.2.3]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs/Messages d'erreur
      description: Copiez-collez les logs ou messages d'erreur pertinents
      placeholder: |
        Collez ici les logs de la console, messages d'erreur, stack traces...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Vidéos
      description: Si applicable, ajoutez des captures d'écran ou vidéos
      placeholder: Glissez-déposez vos fichiers ici ou collez des liens...

  - type: textarea
    id: additional
    attributes:
      label: ℹ️ Informations supplémentaires
      description: Tout autre contexte utile pour comprendre le problème
      placeholder: Contexte supplémentaire, solutions tentées, liens vers des ressources...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Vérifiez que vous avez bien...
      options:
        - label: Vérifié que ce bug n'a pas déjà été signalé
          required: true
        - label: Testé sur la dernière version
          required: true
        - label: Fourni toutes les informations demandées
          required: true 